import type { Metadata } from "next";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { jostFont } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jostFont.variable}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
